name: ดู+อนาฅต EP.1-4 ละคร เต็ม เรื่อง ตอนที่ ดูสดออนไลน์ฟรี Netflix
description: This is an action to assign yourself to an issue for a repo you are not a contributor to.
author: Brian Douglas
branding:
  icon: 'thumbs-up'
  color: 'white'

inputs: 
  message:
    description: 'Message to prospective contributor'
    required: false
    default: ''
  issueCurrentlyAssignedMessage:
    description: 'Message to contributors if issue is already assigned'
    required: false
    default: 'The issue you are trying to assign to yourself is already assigned.'
  trigger:
    description: 'The string that triggers the action'
    required: false
    default: '.take'
  token:
    description: 'The GitHub PAT used to authenticate when updating the Issue'
    required: true
